### ISSUE TITLE
[/creating-manifest/basic-configs/:Slava]: Addons will be... - Incorrect.
Replace with:
```Ad...

### ISSUE THREAD

**Issue by vlobzakov** [vlobzakov/docs#56]
## Target page:
[http://cloudscripting.demo.jelastic.com/creating-manifest/basic-configs/](http://cloudscripting.demo.jelastic.com/creating-manifest/basic-configs/)
## Reporter:
Slava
## Comment:
Incorrect.
Replace with:
```Addons will be installed after environment installation but before  onInstall action.```
## Selected text:
nodeGroup [optional] - the defined node layer. A docker-based containers can be predefined in any custom node group.
displayName [optional] - node's display name (i.e. alias)
extip [optional] - attaching public IP address to a container. The default value is 'false'.
addons [optional] - a list of addons, which will be installed in current nodeGroup. Addons will be installed after environment installation and onInstall action will be finished. More details here
tag [optional] - an image tag for dokerized Jelastic templates with nodeType parameter. Full list of supported tag here.
scalingMode [optional] - stateless or stateful scaling mode, the possible values are 'NEW' or 'CLONE' respectively. The default value is 'CLONE' for nodeGroup types: bl,cp,vds. For the rest of nodeGroup types the default value is 'NEW'.

**Comment by SlavaKatiukha** [comment]
```Addons will be installed after environment installation and onInstall action will be finished.```
replace with 
```
Addons will be installed after environment installation but before onInstall action.
```
