### ISSUE TITLE
[/creating-manifest/events/:nodeType is recognized as nodeGroup]: onAfterRestartNode [apache2]:  - SUBSCRIBE: {"appUniqueName":"6...

### ISSUE THREAD

**Issue by vlobzakov** [vlobzakov/docs#62]
## Target page:
[http://docs.cloudscripting.com/creating-manifest/events/](http://docs.cloudscripting.com/creating-manifest/events/)
## Reporter:
nodeType is recognized as nodeGroup
## Comment:
SUBSCRIBE: {"appUniqueName":"6fc53545-0d94-48c5-890e-8053e689e023","filter":{"nodeGroup":"apache2"},"subscriberKey":"onAfterRestartNode [apache2]","envAppid":"db3a34316a9b98fd7b4a4905503869c9","topic":"application.env/AfterRestartNode","app_id":"e662ff9d-db43-487f-967a-e45c4ba6b490"}

 Although onAfterRestartNode [nodeType:apache2] works fine.
## Selected text:
'New Compute node has been added'
>>
/tmp/result.txt

```
onAfterRestartNode [apache2]:
```

  cmd [cp]: 
echo

**Comment by SlavaKatiukha** [comment]
```onAfterRestartNode [apache2]```
should be changed to:
```onAfterRestartNode [nodeType:apache2]```

**Comment by vlobzakov** [comment]
events page updated http://docs.cloudscripting.com/creating-manifest/events/#events-filtering

**Comment by vlobzakov** [comment]
fixed
