### ISSUE TITLE
[/creating-manifest/visual-settings/:host is not correct example]: valueField: host ... - это весь список...

### ISSUE THREAD

**Issue by vlobzakov** [vlobzakov/docs#64]
## Target page:
[http://docs.cloudscripting.com/creating-manifest/visual-settings/](http://docs.cloudscripting.com/creating-manifest/visual-settings/)
## Reporter:
host is not correct example
## Comment:
это весь список полей, которые можно использовать    
                    'iconCls',
                    'isRunning',
                    'shortdomain',
                    'displayName',
                    'appid',
                    'domain',
                    'region',
                    'isDisabled',
                    'disabledMessage',
                    'rightIconCls',
                    'env'
для hostpicker нету смысла менять valueField
лучше его вообще не указывать в доке
именно valueField
пусть оно будет только для envlist
## Selected text:
Hostpicker
    editable: 
true
    valueField: 
host

**Comment by SlavaKatiukha** [comment]
remove valueField from hostpicker examples

**Comment by vlobzakov** [comment]
fixed
